# Example: Go Application Pipeline
# Copy this to your app's .github/workflows/pipeline.yaml

name: Pipeline

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
      - 'hotfix/**'
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy to environment'
        type: choice
        options:
          - dev
          - stg
          - prd
        required: false

env:
  APP_NAME: my-go-app
  PROJECT: platform

jobs:
  pipeline:
    name: Pipeline
    uses: mrops-br/gha-workflows/.github/workflows/_pipeline-golang.yaml@main
    with:
      app-name: ${{ env.APP_NAME }}
      project: ${{ env.PROJECT }}
      gitops-repo: mrops-br/gitops-${{ env.PROJECT }}
      go-version: '1.23'
      working-directory: '.'
      dockerfile: 'Dockerfile'
      enable-lint: true
      enable-test: true
      enable-coverage: true
      deploy-environment: ${{ inputs.environment }}
    secrets: inherit
