# Example: Full-Stack Node.js Application
# Use case: Complete CI/CD with testing, building, and deployment to Kubernetes

name: CI

on:
  push:
    branches: [main, develop, 'release/**', 'hotfix/**']
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: choice
        options:
          - dev
          - stg
          - prd
        required: false

# Prevent duplicate runs: cancel in-progress runs when new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APP_NAME: devportal-api
  IMAGE_NAME: mrops-br/devportal-api
  PROJECT_NAME: devportal

jobs:
  build-and-deploy:
    uses: mrops-br/gha-workflows/.github/workflows/_pipeline-nodejs.yaml@main
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write
    secrets: inherit
    with:
      # Application configuration
      app-name: ${{ env.APP_NAME }}
      image-name: ${{ env.IMAGE_NAME }}
      project-name: ${{ env.PROJECT_NAME }}

      # Node.js configuration
      node-version: '20'
      package-manager: 'npm'  # or 'yarn', 'pnpm'

      # Build configuration
      working-directory: '.'
      dockerfile: Dockerfile
      registry: ghcr.io

      # CI options (all enabled by default)
      enable-lint: true
      enable-test: true
      enable-coverage: true

      # Deployment override (manual trigger only)
      deploy-environment: ${{ inputs.environment }}

      # Runners
      ci-runner: 'ubuntu-latest'
      build-runner: 'shared-runners'

# Git Flow behavior:
# develop → Lint, test, build, push (dev-latest), deploy to dev
# release/1.2.0 → Lint, test, build, push (1.2.0-rc), deploy to stg
# hotfix/1.2.1 → Lint, test, build, push (1.2.1-hotfix-rc), deploy to stg
# main → Lint, test, build, push (latest), manual deploy to prd
# PR → Lint, test, build (validate only, no push/deploy)

# GitOps Integration:
# After successful build, the workflow updates:
# gitops-devportal/devportal-api/overlays/<env>/kustomization.yaml
# with the new image tag, then syncs ArgoCD.

# Required secrets (organization level):
# - ARGOCD_AUTH_TOKEN - ArgoCD API token
# - ARGOCD_SERVER - ArgoCD server URL (e.g., argocd.example.com)
# - CICD_USERNAME - Container registry username (GitHub username or org)
# - CICD_TOKEN - Container registry PAT with read:packages scope
