# Example: Node.js Application Pipeline
# Copy this to your app's .github/workflows/pipeline.yaml

name: Pipeline

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
      - 'hotfix/**'
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy to environment'
        type: choice
        options:
          - dev
          - stg
          - prd
        required: false

# NOTE: This triggers on both push and pull_request to ensure:
# - PRs are validated before merge (pull_request trigger)
# - Direct pushes are validated and deployed (push trigger)
# The workflow logic handles deployment differently based on event type

# Prevent duplicate runs: cancel in-progress runs when new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APP_NAME: my-nodejs-app
  PROJECT: devportal

jobs:
  pipeline:
    name: Pipeline
    uses: mrops-br/gha-workflows/.github/workflows/_pipeline-nodejs.yaml@main
    with:
      app-name: ${{ env.APP_NAME }}
      project: ${{ env.PROJECT }}
      gitops-repo: mrops-br/gitops-${{ env.PROJECT }}
      node-version: '20'
      package-manager: 'npm'
      working-directory: '.'
      dockerfile: 'Dockerfile'
      enable-lint: true
      enable-test: true
      enable-coverage: true
      deploy-environment: ${{ inputs.environment }}
    secrets: inherit
